### PR TITLE
Support RN 0.47 & below

### PR DESCRIPTION
**Pull request by pewh**

### CODE REVIEW

**Comment by itinance** [comment]
Thank you!

**Comment by itinance** [comment]
Just released with v1.1.0 
https://github.com/itinance/react-native-sha256/releases/tag/v1.1.0

**Comment by pewh** [comment]
Hello,

Is there an ETA about releasing v1.1.0 to npm? Thanks.

**Comment by itinance** [comment]
Thanks for asking. Just published.

**Pull request merged**
